# Generated by Django 5.2.10 on 2026-03-13 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('used_password_type', models.CharField(max_length=20)),
                ('easier_to_remember', models.CharField(max_length=20)),
                ('faster_to_type', models.CharField(max_length=20)),
                ('real_life_choice', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='password_type',
            field=models.CharField(choices=[('text', 'Text'), ('emoji', 'Emoji')], max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password_type',
            field=models.CharField(choices=[('text', 'Text'), ('emoji', 'Emoji')], max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='useraccount',
            unique_together={('username', 'password_type')},
        ),
    ]
