# Generated by Django 5.2.10 on 2026-03-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_surveyresponse_alter_loginattempt_password_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='password_type',
            field=models.CharField(choices=[('text', 'Text'), ('emoji', 'Emoji'), ('mix', 'Mix')], max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password_type',
            field=models.CharField(choices=[('text', 'Text'), ('emoji', 'Emoji'), ('mix', 'Mix')], max_length=10),
        ),
    ]
